### PR TITLE
Qt 5 Port

### LINKED ISSUE #27: NifSkope.pro file cleanup
NifSkope.pro should be reorganized and restructured to better operate between platforms, individual machines, and compilers.  Dependency management should be improved.
### Issues.
1. There is an incompatibility with the `NIFSKOPE_VERSION` and `NIFSKOPE_REVISION` macros between Qt Creator and VS 2010-2012.  Also, VCPROJ files do not get generated optimally in addition to this macro formatting error.  Visual Studio should be somehow targeted directly.  (See Below)  
2. The following defines should be looked into:
   - `USE_GL_QPAINTER`
   - `EDIT_ON_ACTIVATE` (alt: `Q_OS_WIN`)
   - `NO_MESSAGEHANDLER` (alt: `QT_NO_DEBUG`)
   
   I would prefer to allow stats rendering on all builds, so `USE_GL_QPAINTER` could be done away with.  Also, `EDIT_ON_ACTIVATE` may be a relic that is not even needed anymore.  
   ---
### Goals
1. Use QT_INSTALL_BINS to find and copy DLLs to build folder _when dynamic_.  Ignore when static.
2. Copy shaders, lang folders to build dir.  
   - Look at INSTALLS option  
   - Alternatively copy to PWD_OUT with QMAKE_POST_LINK  
3. Create make targets for NSIS, docsys, doxygen, etc.
4. Clean up the build dir significantly using UI_DIR, MOC_DIR, OBJ_DIR, RCC_DIR to put them in appropriate subdirs.
5. Differentiate between MSVC builds by Visual Studio and those by Qt Creator.  Checking for `*msvc*` scope does not do this alone, though one can test if the build is a "shadow build".   Qt Creator builds outside of the project root by default.  Visual Studio does not.
6. Setting up 32-bit / 64-bit compiler scopes should be looked into.  Qt precompiled libraries come in 32 and 64-bit.  However, static compilation should be an option for Qt, and we should build our own 32- and 64-bit Qt libs to link against.
7. Consider putting flags in place to enable C++0x / C++11 support for the compilers that can use it.  Like 32/64bit code this would be just put in with the off chance that the source will utilize such features in the future.  There are quite a few nice things about C++11 so it might eventually sneak into the codebase.  
   
   See:
   - http://qt-project.org/doc/qt-5/qmake-advanced-usage.html
   - http://paulf.free.fr/undocumented_qmake.html
   - https://stackoverflow.com/questions/3984104/qmake-how-to-copy-a-file-to-the-output
     ---
#### Task List
- [x] Clean up defines.  
- [x] Make targets for docsys, doxygen, ~~NSIS~~ (Create its own ticket).  
- [x] Split dependencies into their own config blocks.  
- [x] Copy necessary files and folders to build directory.  
- [x] Deal with static vs dynamic builds, e.g. copying DLLs to build dir.  
- [x] Reorganize compiler/platform scopes.  (Only minor work, later work needed)
#### Deferred Tasks (Will make future ticket)
- ~~Solve macro incompatibilities between Visual Studio and Qt Creator _et al._~~ Seems to have fixed itself?  
- ~~Add Visual Studio specific code so that VC++ project files are created correctly.~~ Seems to have fixed itself?  
- Lay groundwork for future 32-bit / 64-bit specific builds, flags for C++0x/C++11 support.  
#### Tracking

Refactor Progress #32 

---

I have to edit the source to get rid of the ridiculous macro incompatibility.

```
#define VERSION QString(NIFSKOPE_VERSION).replace("\"", "")
#define REVISION QString(NIFSKOPE_REVISION).replace("\"", "")
```

I add an additional set of quotes so that VS2010+ stops erroring during compile.  I then run it through this macro so that the strings come out the same no matter what platform it's built on.

### LINKED ISSUE #28: Qt 5 Port
Qt 4.8 is becoming antiquated. Porting to Qt 5 will ease some issues regarding compilation, by having more current tools and packages to work with.  There are of course many other benefits but it is pointless listing them.

I have already begun, but there currently a few issues.  I disabled a few non-essential elements temporarily.  These are due to some methods and classes going obsolete.
### Issues

See: 
- [C++ Api Changes](https://qt-project.org/doc/qt-5.0/qtdoc/sourcebreaks.html)
- [Transition from Qt 4.x to Qt 5](http://qt-project.org/wiki/Transition_from_Qt_4.x_to_Qt5)
- [Porting from Qt 4 to Qt 5](http://www.kdab.com/porting-from-qt-4-to-qt-5/)
##### QFSFileEngine, QAbstractFileEngine, QAbstractFileEngineIterator, and QAbstractFileEngineHandler are no longer public.

This is the basis of the FSEngine code, and the way of opening resources (BSAs).  Some alternative needs to be found.

~~**Update:**  I believe we are going to decide to take this out for the time being.  It didn't appear fully implemented to begin with, and as far as I could tell only allowed you to treat _uncompressed_ BSAs as if they were a directory, therefore accessing textures for the models without needing the loose files.~~

---
##### QSystemLocale is not public anymore. `RESOLVED`

This is a non-issue.  `NifSystemLocale` extends this class, but as far as I can tell it's never actually used.  If it were to be used `QLocale` is an option.
##### toAscii() and fromAscii() Methods are deprecated `RESOLVED`

Simple enough.  Just replace with `toLatin1()` / `fromLatin1()`.
##### QIcon() constructor changes `RESOLVED`

You can no longer give QIcon() a raw string.  You must wrap it with a QPixMap() constructor.
###### Affected Methods/Files:
- spells/headerstring.cpp@L73
- spells/light.cpp@L61
- spells/material.cpp@L101
- spells/stringpalette.cpp@L78
- spells/texture.cpp@L157
- spells/transform.cpp@L277
- widgets/colorwheel.cpp@L118
##### QWidget::setShown() is no longer forwarded to ::setVisible() `RESOLVED`

QWidget::setShown() is part of an ancient Qt3Support API which no longer exists as of Qt5. 
###### Affected Files:
- widgets/valueedit.cpp
##### QObject::trUtf8 and QCoreApplication::Encoding enums are deprecated. `RESOLVED`

~~There is one location in the code where this applies, and the solution is simply removing that parameter as it's now that way be default.  So a non-issue.~~  I can't even find where I made this change in the code...  :thought_balloon:   I know that it was an issue during compile, but I've scoured through every change in my commits and I can't seem to find it.

These above issues are all forward-compatible changes.  They could be fixed in the Qt 4 branch.

---
#### Miscellaneous

There are a few other odd errors I need to look into.  I will comment on these below.
#### Tracking

Refactor Progress #32

### LINKED ISSUE #31: Project Restructure
[WIP]

```
nifskope
+---build
|   *.bat
|   *.in
|   *.sh
+---dep
|   *.dll
+---docsys @ cf44594
+---include [Optional?]
+---install
|   +---linux-install
|   +---win-install
+---lib
|   +---fsengine
|   +---NvTriStrip
|   +---qhull @ 60d5581
+---res
|   +---icon [Move current resources to icon subdir?]
|   +---lang
|   |   *.ts
|   +---shaders
|   |   *.frag
|   |   *.prog
|   |   *.vert
|   +---ui
|   |   *.ui
|   *.ico
|   *.png
|   *.qrc
|   *.qss
|   *.rc
+---src
|   +---gl
|   +---importex
|   +---spells
|   +---ui
|   +---widgets
|   *.cpp
+---test
|   .gitattributes
|   .gitignore
|   .gitmodules
|   CHANGELOG.TXT [Change to GitHub Readme format?]
|   LICENSE.TXT [Change to GitHub Readme format?]
|   TODO.TXT [Legacy?]
|   VERSION [Put in \build instead?]
```

I put some comments in brackets.  To elaborate:
- Icon PNGs currently in `resources` should possibly be moved to their own subdir `res\icons`
- Include directory optional?  NifSkope.pro might be sufficient in giving anything under `lib` a public interface.
- Change TXT files to GitHub readme format?
- Remove TODO?  Take anything useful and turn it into an issue.
- Put VERSION in `build`?  Depends on if the .PRO should go in `build` or the root.

Changes will need to be reflected in:
- NifSkope.pro
  - Change paths to source, resources, headers, libs
  - If using separate include dir, add to the path so header includes can remain simple
- .gitmodules - The submodules will need their "path" value changed
#### Tracking

Refactor Progress #32

### LINKED ISSUE #36: FSEngine Refactor
FSEngine relies on API that has become private in Qt 5.  To replace it this API first needs to be stripped out and then refactor wherever the code has assumed the virtual filesystem.  
#### [experimental/fsengine](https://github.com/jonwd7/nifskope/commits/experimental/fsengine)

I have it solved for the most part.  The "Resource Files" works just as before, ~~but there are a few other places (Spells and such) that assume the virtual filesystem.~~
##### Replace QAbstractFileEngine with QFile/QFileInfo

Everything necessary can be replicated using QFile and QFileInfo.
##### Remove FSArchiveEngine, FSArchiveHandler, BSAIterator

These were classes to extend the virtual filesystem and utilized QAbstractFileEngine, QAbstractFileEngineHandler, and QAbstractFileEngineIterator, respectively.
##### Add QByteArray member `data` to Tex struct

Each texture that gets loaded is represented as a Tex object.  For textures which load from BSAs, store the raw data directly on the Tex.  Elsewhere, check if the data is not empty.  If the data is not empty, the texture is not on the filesystem.

Wherever a QFile is assumed (to read texture data), add a QBuffer branch which will read the raw data on the Tex into memory.
##### Related
#28 Qt 5 Port
#### Tracking

Refactor Progress #32

### LINKED ISSUE #38: Dev- and Linux-specific code
There is a lot of code that searches for directories and such that is specific either to dev builds (builds within the repo source dir) or the Linux platform (`/usr/share`) without any kind of preprocessor defs.

Personally, my take is that going forward, the NifSkope.pro file (#27) will be responsible for handling the shuffling around of data during a build.  I already copy the required DLLs (if on Windows), the shader and lang folders, etc. to the build directory using QMAKE_POST_LINK.  I think that qmake is perfectly acceptable for the Linux build as well, and it would make the most sense to have one platform-agnostic makefile.

Furthermore, if any of this dev-specific code is left in at all, the paths need to change as the source has been restructured (#31).

### PR DESCRIPTION
**Pull request by hexabits**
### Overview

Qt 5 Port - Closes #28
NifSkope.pro file cleanup - Closes #27
Project Restructure - Closes #31
FSEngine Refactor - Closes #36
Dev- and Linux-specific code - Closes #38

<sup>_(Hopefully I [got the syntax right](https://github.com/blog/1506-closing-issues-via-pull-requests))_</sup>

Only thing I can think of to bring up for discussion is the inclusion of `/build/doxygen/tags` folder (0ae1f9f6492f96ed538835ee29addbda781ab814), which includes tag files for Qt 5, which is just a long list of classes/class members in an XML file in order to make the the NifSkope API documentation much easier for developers to browse.

I'll provide [NifTreeView as an example](https://dl.dropboxusercontent.com/u/9491126/apidocs/html/class_nif_tree_view.html), since the main NifSkope class has a scary collaboration diagram.   You can browse the other docs if you want, but notice that anything with a Q\* is clickable in the inheritance/collaboration, and also in all the member descriptions, and sends you to the official documentation.   Furthermore what I love is it lists all the [inherited member functions](https://dl.dropboxusercontent.com/u/9491126/apidocs/html/class_nif_tree_view.html#pro-methods).  

So, ignoring the fact that it's ~11MB I think it's very useful.   I guess that I could also put them into a 7z which is ~350KB... and then have my doxygen make target decompress the archive before running doxygen.  And add *.tags to the .gitignore.  But I didn't think of it until now... :)   Also, the .tags files are probably why the additions number is so crazy. (+243,967, -38,901)

### CODE REVIEW

**Comment by neomonkeus** [comment]
If you want to add in the tags stuff you can, just add a new commit to your branch. The Pull Request pulls in everything automatically up to the point merge is clicked. This is really good when people spot things while reviewing, additional changes can be put through.

Yeah I say that commit with the tag files, they were huge amounts of files and additions/deletions

**Comment by hexabits** [comment]
It's already there.  Done in `[Restructure] Doxygen Improvements` (0ae1f9f)

I was mostly bringing up "Are the loose files worth the size cost and should I zip them?".  Also they inflate the additions considerably since the code additions/deletions are counting them. 

Thing is, at this point, I don't know how to gracefully undo the change.  It was 15 commits ago.   I think I can somehow rewind to that commit, delete the files from all the commits, then play that on top,  then add the 7z version instead.   So that the files aren't forever stuck in the repo history.   But then I would also need to modify the doxygen target to unzip the 7z, in a multiplatform way.

**Comment by neomonkeus** [comment]
This should be useful in that case - http://stackoverflow.com/questions/37219/how-do-you-remove-a-specific-revision-in-the-git-history?answertab=active#tab-top. Removing out anything that can be auto-generated is preferred if its not too much effort. Try locally as worst case scenario you just delete the branch locally and pull it down again.

**Comment by hexabits** [comment]
There is also 

```
git filter-branch --tree-filter "rm -f ./build/doxygen/tags/*.tags" c4214d4..HEAD
```

~~Or something close, haven't tested.~~ Seems to work.  Because I read rebase won't actually get rid of the files from the history, meaning my repo is always going to have the extra 10MB hanging around.  :)

Not a huge deal obviously. 

As for auto-generated...  If you mean like the doxytag script that used to be in the repo,  doxytag is obsolete now.  It's not even included with Doxygen so there is no way of generating tagfiles without actually processing source code with Doxygen.  Processing the Qt 5 source clearly isn't going to be an efficient option.  :)

So, I can zip them up and add *.tags to .gitignore.   Then for the doxygen target if I really can't manage to extract the zip in an easy cross-platform way, just throw up an error and tell them they have to unzip that file first.

**Comment by neomonkeus** [comment]
How should we handle this though if it is obsolete and our source changes over time or should we take this up as a separate issue?

**Comment by hexabits** [comment]
Well the tags are specific to Qt 5.2.  The API doesn't change any between patch levels (5.2.0 > 5.2.1) and between 5.2 and 5.3 it will barely change any.   So, it actually only matters if the Qt version target changes on our end.  Our source can change as much as it likes. 

These .tags files do get built during the actual make html_docs (or whatever) phase when building the Qt libraries.  So I built the .tags files myself but it requires the full Qt source, and you pretty much have to compile a full version of Qt to get them.

**Comment by neomonkeus** [comment]
This good to go then.

**Comment by hexabits** [comment]
@neomonkeus Yeah.  You can call in other people to look through it too if you want.  I know @skyfox69 is busy though, and I'm not sure who else is active. :)

I'm working through some refactor stuff now, but it can all get its own pull request.

**Pull request merged**
