### PR TITLE
Skyrim Support:  Collision, Spells, Edit UV fixes

### PR DESCRIPTION
**Pull request by hexabits**
Combination of several fixes for Skyrim NIF changes.  Also, bhkCompressedMeshShape display for the render view.

### CODE REVIEW

**Comment by hexabits** [comment]
Issues:  #1 #3 #4 #6 #7

**Comment by skyfox69** [comment]
@jonwd7: Great work! I saw you added some fixed factors (70.0f, 10.0f) into source code to resize collision mesh to model one. They fit perfectly for Skyrim meshes but are they compatible with Oblivion and Morrowind, too? Think they worked without the factors and now fixed ones independend of NIF version...? Could you provide a binary version of your new NifSkope? Can't setup a NifSkope environment here...

**Comment by neomonkeus** [comment]
@skyfox69 - There is a version check. Line 763  - https://github.com/jonwd7/nifskope/blob/4307d6ba40316e01cc0b332fcdcf37381d49520a/gl/glnode.cpp#L763

**Comment by skyfox69** [comment]
Sorry, I'm blind :-(  Was late last night, early this morning. I should go to bed right now... Sorry - forget my comment...

**Comment by skyfox69** [comment]
But a binary version would be great - or did I missed another hint, too? ;-)

**Comment by hexabits** [comment]
@skyfox69 Yeah, what @neomonkeus said.  There aren't any factors left that aren't conditional.  `havokScale` is 1.0 for everything that is not Skyrim.

I'll get a binary together from the develop branch once I sync mine.

**Comment by hexabits** [comment]
@skyfox69 @neomonkeus 

[Here is the binary](https://drive.google.com/file/d/0B9F4jSOO-JcpR3dVVFU0YzM2eUk/edit?usp=sharing) for the develop branch.

I found recently that the config file doesn't put the registry settings in its own folder per version, so running this with 1.1.3 installed will reset the UI settings.   I plan on fixing the registry issue too.

**Pull request merged**
