### PR TITLE
Script support

### PR DESCRIPTION
**Pull request by tschilkroete**
This adds scripting to nifskope that allows to edit a nif automatically.It should make it way easier to export a lot of models at once. If nifskope gets started with a *.nss file it will be automatically executed.
A *.nss file has this structure:

//Comment line

//DO_FOR executes the script for every file in this folder.
//So this script gets executed for every nif file in this directory
//It also fills:
//$(FILENAME) The filename of the current file
//$(FILEPATH) The full path to the current file
//$(DIRECTORY) The current directory
//$(BASENAME) The filename without extension
DO_FOR *.nif
LOAD $(FILEPATH)
IMPORT 0 testCube.3ds

COPYB 17 //Copies the branch 17
PASTEB 0 //Pastes it into branch 0
REMOVEB 16 //Removes branch 16
CHANGE 16 Name TO $(BASENAME) //Changes property Name of block 16 the filename
CHANGE 14 Textures[0] TO textures/$(BASENAME).dds //Changes the texture paths
CHANGE 14 Textures[1] TO textures/$(BASENAME)_n.dds

SAVE $(DIRECTORY)/skyrim_$(FILENAME) //Saves the current file

### CODE REVIEW

**Comment by hexabits** [comment]
I saw this and looked it over it last week but I haven't really had time to formulate an opinion fully.

I do appreciate other contributions, so I don't want this to be taken the wrong way, but this is an awfully large amount of code to get a pull request with no prior discussion.  A feature of this magnitude probably could have used a ticket first.  At the very least a higher level discussion about the features and maybe the syntax of the batch file.

(Edit:  So, I would suggest if you plan on contributing longterm, that you make an account at the NifTools forums.  Also I can give you access to our Trello so that you could see what tasks I have queued up that you might want to try tackling.)

Namely, there is some obj and 3ds integration that I can see, and we were pretty much planning on scrapping the existing code and starting over.  None of the people who wrote it are around anymore and it's too broken for me to understand where to fix it.  So, once I go to pull out the old import/export code,  I'm stuck not knowing how to reintegrate new code with this feature.

This is definitely useful though, and I like where it's going.  I haven't compiled it yet to try it out, so I'm not sure if this is how it works, but I'd rather the .nss be a last resort of sorts, or just the way to share the actions with someone else.   I'd prefer the UI to let you add and remove various actions like [batch image processors](http://www.xnview.com/assets/img/screenshots/xnconvert-win-02.jpg). The actions would also include any batchable Spells.

**Comment by tschilkroete** [comment]
I agree that I should have made a discussion on how to implement that first. Sorry for that. I'll make a thread on the NifTools forums.
I tried to change as less code as possible, however the implementation of the import/export code has no way to just import a model without showing any dialogs so I had to change that. Nothing else has changed. I think the UI is a great idea and I would love to make this a fully working feature.

**Comment by srgraham** [comment]
Any plans to merge this? I've been trying to mass export all fallout 4 lod .nif files using any tools I could find, but have been unsuccessful. Following the discussion at http://niftools.sourceforge.net/forum/viewtopic.php?f=4&t=6170 , it seems like this is a good candidate for inclusion and would be really helpful for me in particular.

**Comment by neomonkeus** [comment]
@srgraham - Haven't seen much activity on this PR for some time. It will need to be rebased/updated to account for divergent code base as there is branch conflicts.

@jonwd7 - looking at the forum thread here you seem happy with the progression but not what the current state of things are like due to ongoing Fo4 work.

**Comment by tschilkroete** [comment]
Maybe this is something for a later date after fo4 work and the import/export is finished. 
 @jonwd7 Let me know if I can help with anything.

**Pull request closed without merging**
