### PR TITLE
2.0dev7

### LINKED ISSUE #18: Header Strings enhancements
Block names are stored in the header and referenced by index.  This reference gets muddled when copy/pasting blocks into new NIFs.  It does not bring the actual strings over with it, but references the string at the same index.

It may be possible to reconcile differences between the string indices by adding all the strings which are needed by the block/branch to the end of the strings and modifying the pasted blocks' indices to point to the new location.

However such repeated actions over time could cause a lot of header string cruft.  Might be worth looking into to make a Spell which removes unused strings.
## Task List
- [x] Source -> Destination header string reconciliation and integration.
- [x] Spell which removes unused Strings.
- [x] ~~Allow reorganization of Strings.~~ Deferred for new dedicated ticket
- [x] ~~Improve method of reassigning Strings (Clicking the "TXT" button is a little obscure)~~ Deferred for new dedicated ticket (same ticket as above item)

### LINKED ISSUE #55: Auto-Expand certain blocks
Some blocks should be expanded by default to improve usability.  For example, the "Textures" array in BSShaderTextureSet.

It is possible to allow the end user to choose what blocks they want expanded by default by providing a filter box in the Settings window, in the same fashion as "Cull Nodes By Name".

### LINKED ISSUE #100: Unknown Property: NiShadePropery
Just for info: I only opened this issue, because this is still a issue and i have found no open "Issue" on this one.

<Used Version: 2.0.0 Pre-Alpha6>
<Gamebryo, Version 20.3.0.9>

[One of the files wich have this Property.zip](https://github.com/niftools/nifskope/files/629618/One.of.the.files.wich.have.this.Property.zip)

### LINKED ISSUE #106: Nifskope can't read CK-generated precombined meshes
Thank you very much for updating nifskope so it can read the Bethesda-made precombined nifs. It's painful figuring out what parts match up to what references, but if I really want to I can edit them.

However, the ones generated by the CK use a completely different format apparently. So they are not only 5-10 times larger than the Bethesda-made ones, but nifskope can't read them. When I open a CK-made precombined, it gives two warnings:

```
File: 
Function: 
Line: 0
Category: nifskope.nif
Message:

"Unknown property: BSShaderTextureSet"
```

and 

```
warning: block 3 (BSPackedCombinedGeomDataExtra) not inserted!
device position incorrect after block number 3 (BSPackedCombinedGeomDataExtra) at 0x228 ended at 0x228 (expected 0x370)
device position incorrect after block number 4 (BSLightingShaderProperty) at 0x370 ended at 0x374 (expected 0x3fc)
device position incorrect after block number 5 (BSShaderTextureSet) at 0x3fc ended at 0x428 (expected 0x445)

```
Any chance of an update to let use clean up the CK-made precombineds for those of use crazy enough to try?

Currently using most up-to-date version I can find: 2.0.dev6 (revision 1d9d0d6)

### LINKED ISSUE #124: BSSkyShaderProperty Error
Nifscope doesnt recognise this Property as valid and throws tons of error requesters when working on the clouds.nif file in meshes/sky each time a change is done.

### PR DESCRIPTION
**Pull request by hexabits**
#### UI

- New UI theming engine.
    - New Dark/Light theme with user customizeable palettes.
    - Toolbar icon size selection (in **Settings > General > Theme**)
- Copy/Paste branch overhaul
    - **Strings maintained on copy/paste** for 20.1.0.1+.  Each block has its string indices updated with a new string brought over from the source file.  See [gallery below for an example](#gallery).
    - Relaxed the linking restrictions on Paste Branch when a link points to the root node. This allows NiCollisionObject branches to be pasted onto other NIFs more easily for example.
    - Pasting a branch is now 20-30x faster, more so for extremely deep branches.
    - NiCollisionObjects are now auto-linked if pasted on top of an NiAVObject (node or trishape)
- Add New Ref for None refs:
    - Filtered by the valid types for that link.  Interpolator and Controller Refs have additional filtering which only shows the valid types for that block.
base-profile-12 08 2017---16 36
- New row copy/paste (incl. multi-row paste). Ideal for quickly pasting types like Vector3 or Color4.
    - Click single row, Ctrl + C, click one or many rows, Ctrl + V
    - Fully undoable. 
    - Caveat: Strict type validation (e.g. cannot paste int<->uint or uint<->ushort)
    - NOTE:  You **cannot** multi-copy multiply selected rows.  Only the first selected value is copied. You can only *paste* a single value to multiple rows.
base-profile-12 17 2017---23 59 
- New array-compound copy/paste.  Any flat array or flat compound i.e. an *expandle item with no more expandable items under it* can be copied and then pasted on other arrays/compounds.
    - Fully undoable.  An entire array paste is undone/redone as a group.
compoundcp-50 arraycp-50
- Ref arrays (such as Children array on NiNode) can be reordered using Ctrl-Up and Ctrl-Down on individual Refs.
- Icon res upped 2x for high DPI.
- Updated all URLs to NifTools websites, added URLs to the NifTools Discord
- Hold X or Y to constrain axis of motion in UV Editor
- Hold spacebar as alternative to using MMB for panning in viewport
- 'Reject Changes' button for NifBlockEditor windows (e.g. Edit Transform).  Sets the values back to when you first opened the window. 
- Auto-expansion of more items in Block Details.  Modified Textures array expansion to a more general "end array" expansion. Will now apply to Connect Points, etc.  Expand NiSkinPartition partition array always, expand NiQuatTransform in interpolators always, expand Children array of NiNode if relatively small.
- Flags window for editing the vertex attributes for BSTriShape.  It hides the bits that need to be auto calculated from the flags and updates the rest of it after you set them.  It also recalculates the Data Size.  This means you can now turn vertex attributes on/off for FO4/SSE without breaking the NIF.
- Import/Export improvements
    - Import/Export menu options are now disabled dynamically based on the NIF version instead of always disabled.
    - Exports/Imports more shader settings and texture paths for Skyrim and later.  Will create shader properties and texture sets for the newly imported OBJ.
    - BSFadeNode, et al. are now seen as an NiNode for exporting a selection or for parenting an imported mesh.
- Settings > Resources improvements
    - Add archives from the file dialog only if they contain a textures or materials folder, the same as done with the Auto Detect button.
    - Disallowed manual editing of list items in Archives, but maintained it in Paths.
    - Correctly mark the pane as modified for editing list items and toggling Alternate File Paths option.

#### Rendering

- New texture loader.  Supports DX10-header DDS files and BC7, etc.  Is also much faster.
- First stage of renderer rewrite.  Removed many bottlenecks.  NIFs with thousands of blocks could go to 20FPS or lower.  They are now renderered about 3x faster.  Some NIFs with 10,000+ blocks are now 4-5x faster.
- Node axis visualization (Show Axes and Show Nodes must be on).  Lets you see the orientation of a node i.e. how objects under that node will be oriented.
- Reworked segment visualization for FO4 BSSubIndexTriShape.  See [gallery below for an example](#gallery).
- LOD Slider FO4 support (BSMeshLODTriShape)
- RGB Falloff now supported in FO4 shaders
- BSPackedCombinedGeomDataExtra (CK generated _OC NIFs) can now be loaded. The geometry baked into the extra data cannot currently be viewed.
- For skinned shapes, the triangles/strips used for rendering are now the ones from the partitions. So certain NIFs which only had triangles on their partitions will render now and the rendering will be generally more accurate in the event the partition and the shape triangles aren't in sync.
    - Also made a spell which lets you update the shape triangles from the partition triangles (for NiTriShape only so far).

#### Data Management

- Spell updates for SSE/FO4 NIF versions
    - Transform > Apply now works for BSTriShape
    - Texture > Export Template now works for BSTriShape
    - Face/Smooth Normals updated for SSE, incl. skinned meshes.
    - Update Tangents updated for SSE, incl. skinned meshes.
- Spells for managing NiControllerSequence and NiDefaultAVObjectPalette
- Updates for latest nif.xml
    - Major NIF format decoding, esp. in bhk blocks for Bethesda versions, and major non-Bethesda version decoding was done across the board. 
    - Reduced nesting of HavokMaterial, HavokColFilter and constraint descriptor types
        - This fixed the coloring of collision wireframes based on their layer (e.g. static, clutter, biped)
        - This fixed the display of some constraints no longer working. 

#### Fixes

- Fixed **long elusive checkbox list crashing** e.g. when editing bitflags like shader flags
- Fixed cross-platform build issues
- Static analysis fixes and optimizations
- Fixed game detection for 64-bit builds
- Fixed "Close All Windows" (taskbar option) crash
- Fixed display of bhkConvexListShape and sub-shapes in hkPackedNiTriStripsData
- Fixed BGSM/BGEM priority over the shader property blocks for things such as Double Sided, ZBuffer Test, ZBuffer Write
- (32-bit Only) Fixed longstanding bug with MOPP code regeneration.  The byte array was not correctly updated so all binary data created by this spell has always been corrupt.  Confirmed to happen in 1.1.x by a tester.
- Fix texture loading for non-Bethesda games.  The path was being cleaned in a way which Bethesda games require.
- Fixed Update Tangent Spaces for FO4.  Tangents were never updated for FO4, only Bitangents, due to an issue with `set<T>`.
- Fixed Transform > Apply for all NiTri* based NIFs.  It was not transforming Tangents and Bitangents if the Transform had non-identity rotation.  So it was required that you also ran Update Tangent Spaces after.
- Fixed KFM file loading
- Fixed Stripify for large shapes. 
- Selecting rows in very large flat arrays is no longer slow with Row Hiding on.
- Fixed camera motion when changing the default up axis in Render settings.
- Fixed Color3/Color4 behaviors (allows > 1.0, value doesn't show as hex RGB when > 1.0). BSEffectShaderProperty's Color4 alpha most commonly uses values > 1.0.
- Fixed rigid body selection in viewport (clicking on rigid body axes).  Rigid Body axes now turned on/off with Show Axes.

#### Non-Bethesda specific changes

- NiMesh initial rendering support (geometry for versions 20.5+)
- Corrected NiTexturingProperty UV set selection in 20.1+ NIFs, which also applied to NiMesh NIFs.  Lightmaps and such were not getting the correct UV sets so the entire appearance was broken.
- Corrected NiVertexColorProperty vertex color rendering for 20.1+ NIFs.  The information moved to a single Flags field which was not being read by the renderer.  Vertex colors did not show up at all before this fix.
- 20.3.1.1 and 20.3.1.2 support, including the header version which does not have block type strings and only hashes. 
- Usage/Access are retained for NiDataStream with copy/paste
- Fix palettized NiPixelData texture loading

Closes #124 , Closes #106 , Closes #100 , Closes #18 , Closes #55

### CODE REVIEW

**Comment by hexabits** [comment]
I believe AppVeyor may actually need to be bumped up to VS 2017 / C++17.  I believe some C++17 features are now being used.

**Comment by hexabits** [comment]
Actually nevermind, I think it's that I increased the requirement to Qt 5.7 so qmake automatically fails because AppVeyor is using Qt 5.6 right now.  Same with Travis.

**Comment by mirh** [comment]
Appveyor supports up to qt 5.9.1 [actually](https://www.appveyor.com/docs/build-environment/#qt). 

You can read about c++17 and msvc [here](https://docs.microsoft.com/en-us/cpp/visual-cpp-language-conformance) instead (some was already in VS 15)

**Comment by neomonkeus** [comment]
@mirh - fix has already been applied, builds are passing. See the ticks beside each commit.

**Pull request merged**
